In [1]:
import numpy as np

In [2]:
ls = [12, 334, 45, 56, 78, 89, 4.5, 34, 9.09, 34]

In [3]:
arr = np.array(ls)

In [4]:
arr

array([ 12.  , 334.  ,  45.  ,  56.  ,  78.  ,  89.  ,   4.5 ,  34.  ,
         9.09,  34.  ])

In [6]:
len(arr)

10

In [8]:
arr.shape #one dimentional array - vector

(10,)

In [9]:
#range element - last element in range not included
#elemenr 2,3,4
arr[2:5]

array([45., 56., 78.])

In [10]:
arr[1:3] = 44

In [11]:
arr

array([12.  , 44.  , 44.  , 56.  , 78.  , 89.  ,  4.5 , 34.  ,  9.09,
       34.  ])

In [12]:
arr[1:]

array([44.  , 44.  , 56.  , 78.  , 89.  ,  4.5 , 34.  ,  9.09, 34.  ])

In [13]:
arr_slice = arr[3:8]

In [14]:
arr_slice

array([56. , 78. , 89. ,  4.5, 34. ])

In [15]:
arr_slice[:] = 55

In [16]:
arr_slice

array([55., 55., 55., 55., 55.])

In [17]:
arr

array([12.  , 44.  , 44.  , 55.  , 55.  , 55.  , 55.  , 55.  ,  9.09,
       34.  ])

In [18]:
#slice still not an indeoendent 

In [19]:
arr2 = arr.copy()

In [20]:
#thisis a different array

In [22]:
arr2[3] = 777

In [23]:
arr2

array([ 12.  ,  44.  ,  44.  , 777.  ,  55.  ,  55.  ,  55.  ,  55.  ,
         9.09,  34.  ])

In [24]:
arr

array([12.  , 44.  , 44.  , 55.  , 55.  , 55.  , 55.  , 55.  ,  9.09,
       34.  ])

## Two dimentional

In [27]:
arr = np.arange(90)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [29]:
arr.shape

(90,)

In [30]:
arr = arr.reshape(9,10)

In [31]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [32]:
arr.shape

(9, 10)

### slicing

In [33]:
arr[1,1]

11

In [35]:
arr[1][1] #both above and this are the same

11

In [45]:
arr = np.arange(90)
arr = arr.reshape(9,2,5) #9 arrays- each of them 2 by 5

In [46]:
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]]])

In [47]:
arr[0]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
arr[0][0]

array([0, 1, 2, 3, 4])

In [49]:
arr[0][0][0]

0

In [50]:
import random

In [51]:
l1k1=np.random.rand(3,3)
l1k2=np.random.rand(3,3)
l1b1=np.random.rand(1)
l1b2=np.random.rand(1)

In [52]:
l1k1

array([[0.36689551, 0.62351565, 0.29126828],
       [0.20868109, 0.86845413, 0.23767397],
       [0.72392086, 0.56019051, 0.61140996]])

In [54]:
l1k1.shape

(3, 3)

In [53]:
l1k2

array([[0.1429409 , 0.21165126, 0.54167454],
       [0.46052951, 0.64180131, 0.02047327],
       [0.28857147, 0.27881187, 0.41244494]])

In [55]:
l1k2.shape

(3, 3)

In [56]:
l1k1=l1k1.reshape(3,3,1,1)
l1k2=l1k2.reshape(3,3,1,1)

In [57]:
l1k1

array([[[[0.36689551]],

        [[0.62351565]],

        [[0.29126828]]],


       [[[0.20868109]],

        [[0.86845413]],

        [[0.23767397]]],


       [[[0.72392086]],

        [[0.56019051]],

        [[0.61140996]]]])

In [58]:
l1k1[0]

array([[[0.36689551]],

       [[0.62351565]],

       [[0.29126828]]])

In [60]:
l1k1[0][0]

array([[0.36689551]])

In [62]:
l1k1[0][0][0]

array([0.36689551])

In [63]:
l1k1[0][0][0][0]

0.36689550986087116

In [65]:
l1k2

array([[[[0.1429409 ]],

        [[0.21165126]],

        [[0.54167454]]],


       [[[0.46052951]],

        [[0.64180131]],

        [[0.02047327]]],


       [[[0.28857147]],

        [[0.27881187]],

        [[0.41244494]]]])

In [66]:
w1=np.concatenate((l1k1,l1k2),axis=3)

In [67]:
w1

array([[[[0.36689551, 0.1429409 ]],

        [[0.62351565, 0.21165126]],

        [[0.29126828, 0.54167454]]],


       [[[0.20868109, 0.46052951]],

        [[0.86845413, 0.64180131]],

        [[0.23767397, 0.02047327]]],


       [[[0.72392086, 0.28857147]],

        [[0.56019051, 0.27881187]],

        [[0.61140996, 0.41244494]]]])

In [68]:
#Create NumPy arrays
arr = np.array([4, 7, 12])
arr1 = np.array([5, 9, 15])

In [69]:
# Use concatenate() to join two arrays
con = np.concatenate((arr, arr1))
print(con)

[ 4  7 12  5  9 15]


In [70]:
# Use concatenate() with axis
con = np.concatenate((arr, arr1), axis=1)
print(con)

TypeError: concatenate() got multiple values for argument 'axis'

In [72]:
# Create NumPy array
arr = np.array([[4, 6],[9, 13]])
arr1 = np.array([[8, 3],[12, 19]])

# Use np.concatenate() Function
con = np.concatenate((arr, arr1), axis=1)
print(con)

[[ 4  6  8  3]
 [ 9 13 12 19]]


In [73]:
arr

array([[ 4,  6],
       [ 9, 13]])

In [74]:
arr1

array([[ 8,  3],
       [12, 19]])

In [ ]:
con = np.concatenate((arr, arr1), axis=1)
print(con)

### Concatinate

In [75]:
first_array = np.arange(1, 10).reshape(3, 3)
second_array = np.arange(10, 19).reshape(3, 3)

In [76]:
print(first_array)
print(second_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [77]:
print(first_array.shape)
print(second_array.shape)

(3, 3)
(3, 3)


You can concatenate an array on two axes: by row or by column. This is accomplished using the concatenate() method. The concatenate method can merge 1d, 2d, 3d, 4d, and arrays with a higher number of dimensions.

#### Concatenate by Row \
We’ll start by concatenating our two arrays by row. This will align the items in our two arrays by row and merge them into one array:


In [78]:
final_array = np.concatenate((first_array, second_array))
print(final_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [79]:
print(final_array.shape)

(6, 3)


We have specified a tuple inside the concatenate() function. This tuple contains the list of arrays that we want to concatenate. Without any parameters, concatenate() concatenates by row

### Concatenate by Column 
You can use the concatenate method to merge two arrays by column

To do this, we need to introduce a new parameter: axis. By default, this value is 0. This corresponds to the x axis, or the row axis. We can override this value and set it to 1. This will merge our two arrays by column.

In [80]:
final_array = np.concatenate((first_array, second_array), axis=1)
print(final_array)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [81]:
print(final_array.shape)

(3, 6)


### My practice

In [83]:
first_array = np.arange(1, 10).reshape(3, 3, 1, 1)
second_array = np.arange(10, 19).reshape(3, 3, 1, 1)

In [84]:
first_array

array([[[[1]],

        [[2]],

        [[3]]],


       [[[4]],

        [[5]],

        [[6]]],


       [[[7]],

        [[8]],

        [[9]]]])

In [85]:
second_array

array([[[[10]],

        [[11]],

        [[12]]],


       [[[13]],

        [[14]],

        [[15]]],


       [[[16]],

        [[17]],

        [[18]]]])

In [86]:
second_array[0]

array([[[10]],

       [[11]],

       [[12]]])

In [87]:
second_array[0][0]

array([[10]])

In [88]:
second_array[0][0][0]

array([10])

In [89]:
second_array[0][0][0][0]

10

In [90]:
final_array = np.concatenate((first_array, second_array), axis=3)

In [91]:
final_array.shape

(3, 3, 1, 2)