#### Simple RNN

In [1]:
from numpy import array
from keras.utils import to_categorical

In [2]:
line ='now they know how many holes it takes to fill the albert hall.'
chars = sorted(list(set(line))) #18 unique characters

In [3]:
chars

[' ',
 '.',
 'a',
 'b',
 'e',
 'f',
 'h',
 'i',
 'k',
 'l',
 'm',
 'n',
 'o',
 'r',
 's',
 't',
 'w',
 'y']

In [4]:
mapping = dict((c,i) for i,c in enumerate(chars))

In [5]:
mapping

{' ': 0,
 '.': 1,
 'a': 2,
 'b': 3,
 'e': 4,
 'f': 5,
 'h': 6,
 'i': 7,
 'k': 8,
 'l': 9,
 'm': 10,
 'n': 11,
 'o': 12,
 'r': 13,
 's': 14,
 't': 15,
 'w': 16,
 'y': 17}

In [6]:
encoded_line = array([mapping[char] for char in line])

In [7]:
encoded_line

array([11, 12, 16,  0, 15,  6,  4, 17,  0,  8, 11, 12, 16,  0,  6, 12, 16,
        0, 10,  2, 11, 17,  0,  6, 12,  9,  4, 14,  0,  7, 15,  0, 15,  2,
        8,  4, 14,  0, 15, 12,  0,  5,  7,  9,  9,  0, 15,  6,  4,  0,  2,
        9,  3,  4, 13, 15,  0,  6,  2,  9,  9,  1])

In [8]:
len(encoded_line)

62

In [8]:
vocab_size = len(mapping)

In [9]:
one_hot_line =array(to_categorical(encoded_line,num_classes=vocab_size))

In [11]:
one_hot_line.shape

(62, 18)

In [12]:
one_hot_line = one_hot_line.reshape(1,62,18)

In [14]:
one_hot_line[0][0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0.])

In [16]:
one_hot_line[0][61]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

One hot encoding entire senetence based on the characters| same characters get the same encoding

Simple RNN Modeling

In [18]:
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM,SimpleRNN
from keras.layers import Dense


In [35]:
model = Sequential()
# model.add(SimpleRNN(100,stateful=True,batch_input_shape=(None,62,18)))
# model.add(SimpleRNN(100,stateful=True,return_sequences=True,input_shape=(None,62,18)))
model.add(SimpleRNN(100, stateful=False, return_sequences=True, input_shape=(62, 18)))

model.add(Dense(vocab_size,activation='softmax')) #18 unique characters
model.summary()

Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_16 (SimpleRNN)       │ (None, 62, 100)        │        11,900 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 62, 18)         │         1,818 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,718 (53.59 KB)

 Trainable params: 13,718 (53.59 KB)

 Non-trainable params: 0 (0.00 B)

In [36]:
ans = model.predict(one_hot_line, verbose=0)
print(ans.shape)

(1, 62, 18)


In [37]:
print(ans[0,61,:])

[0.04468004 0.03720954 0.06869965 0.06196771 0.03911978 0.03133812
 0.02675151 0.03459295 0.05623053 0.05031937 0.05372349 0.02983955
 0.03828743 0.15587059 0.03390291 0.06060183 0.0968793  0.0799858 ]


In [38]:
modelLSTM = Sequential()
modelLSTM.add(LSTM(100,input_shape=(1,one_hot_line.shape[2])))
modelLSTM.summary()

/Users/h6x/anaconda3/envs/pytorch/lib/python3.11/site-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_17"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 100)            │        47,600 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 47,600 (185.94 KB)

 Trainable params: 47,600 (185.94 KB)

 Non-trainable params: 0 (0.00 B)